apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  labels:
    app: health-check-service
spec:
  type: NodePort
  selector:
    app: health-check-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080